import { GameDefinition, QuizQuestion, PairCard, SwipeCard, RouletteSlice, ChestOption, AppConfig } from '../types';

export const DEFAULT_APP_CONFIG: AppConfig = {
  eventName: 'Feria de Empleabilidad 2025',
  eventDate: new Date().toISOString().split('T')[0],
  welcomeMessage: '¡Demuestra tu potencial y gana premios instantáneos con BancoSol!',
  prizesAvailable: true,
  prizesTotalStock: 50,
  prizesRemaining: 42,
  prizeName: 'Kit de Marca Empleadora BancoSol',
  autoResetSeconds: 25,
  activeGames: {
    maze: true,
    quiz: true,
    roulette: true,
    chests: true,
    pairs: true,
    swipe: true,
    catcher: true,
  },
  quizRequiredCorrect: 4,
  googleSheetsWebhookUrl: 'https://script.google.com/macros/s/AKfycbw-95NnIXQVoCeFQuRwpHbTenDHRKtunVuXg-ePmNqVBagcMyRVKuFK9hrlhaJOebtn/exec',
};

export const GAMES_CATALOG: GameDefinition[] = [
  {
    id: 'maze',
    name: 'Laberinto del Talento',
    subtitle: 'Arcade y Estrategia',
    description: 'Encuentra las 5 competencias clave en 65s usando escudos y esquivando el Burnout.',
    icon: '🧭',
    color: 'from-indigo-600/30 to-blue-600/20',
    accentColor: 'indigo',
    durationText: '60-75 SEG',
    targetDurationSeconds: 65,
    difficulty: 'Estratégico',
    hrTopic: 'Habilidades Blandas, Resiliencia y Enfoque',
    enabled: true,
  },
  {
    id: 'quiz',
    name: 'Quiz Express',
    subtitle: 'Casos y Trivia de RRHH',
    description: '7 dilemas y preguntas sobre liderazgo, feedback y método STAR. ¡Acierta 5!',
    icon: '⚡',
    color: 'from-emerald-600/30 to-teal-600/20',
    accentColor: 'emerald',
    durationText: '60-75 SEG',
    targetDurationSeconds: 70,
    difficulty: 'Desafiante',
    hrTopic: 'Gestión del Talento y Entrevistas por Competencias',
    enabled: true,
  },
  {
    id: 'pairs',
    name: 'Match de Competencias',
    subtitle: 'Memoria y Conceptos Clave',
    description: 'Empareja 6 conceptos y competencias de Recursos Humanos antes de 60 segundos.',
    icon: '🧠',
    color: 'from-cyan-600/30 to-blue-600/20',
    accentColor: 'cyan',
    durationText: '50-65 SEG',
    targetDurationSeconds: 60,
    difficulty: 'Medio',
    hrTopic: 'Diccionario de Competencias y Cultura',
    enabled: true,
  },
  {
    id: 'swipe',
    name: 'Swipe: Mito o Realidad',
    subtitle: 'Decisión Ágil y Aprendizaje',
    description: '8 casos y mitos sobre empleabilidad y clima laboral: Desliza Izquierda (Mito) o Derecha (Realidad).',
    icon: '🔥',
    color: 'from-rose-600/30 to-pink-600/20',
    accentColor: 'rose',
    durationText: '50-65 SEG',
    targetDurationSeconds: 60,
    difficulty: 'Dinámico',
    hrTopic: 'Mitos de Selección, Salarios y Carrera',
    enabled: true,
  },
  {
    id: 'catcher',
    name: 'Colector de Habilidades',
    subtitle: 'Arcade y Reflejos de Talento',
    description: 'Atrapa habilidades blandas, power-ups y técnicas durante 55s evitando el agotamiento.',
    icon: '🎯',
    color: 'from-violet-600/30 to-indigo-600/20',
    accentColor: 'violet',
    durationText: '55-60 SEG',
    targetDurationSeconds: 55,
    difficulty: 'Reflejos',
    hrTopic: 'Competencias del Futuro y Hábitos de Alto Desempeño',
    enabled: true,
  },
  {
    id: 'roulette',
    name: 'Ruleta de la Fortuna',
    subtitle: 'Giro y Reto de Talento',
    description: 'Gira la ruleta de BancoSol y completa el micro-reto de empleabilidad para asegurar tu premio.',
    icon: '🎡',
    color: 'from-orange-600/30 to-amber-600/20',
    accentColor: 'orange',
    durationText: '30-45 SEG',
    targetDurationSeconds: 35,
    difficulty: 'Interactivo',
    hrTopic: 'Oportunidades y Dilemas de Crecimiento',
    enabled: true,
  },
  {
    id: 'chests',
    name: 'Los 4 Pilares Estratégicos',
    subtitle: 'Cliente • Innovación • Sostenibilidad • Talento',
    description: 'Elige uno de los 4 pilares BancoSol, resuelve su desafío de alineación y forja la Llave del Éxito para abrir tu recompensa.',
    icon: '🏛️',
    color: 'from-orange-600/30 via-purple-600/30 to-emerald-600/20',
    accentColor: 'orange',
    durationText: '40-55 SEG',
    targetDurationSeconds: 45,
    difficulty: 'Estratégico',
    hrTopic: 'Pilares Estratégicos, Cultura y Propósito BancoSol',
    enabled: true,
  },
];

export const DEFAULT_QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'q1',
    question: '¿Cuál es la estructura y extensión recomendada para el CV de un postulante?',
    options: [
      '1 a 2 páginas concisas, con logros cuantificables y perfil orientado al rol',
      'Mínimo 5 páginas detallando cada tarea diaria de los últimos 15 años',
      'Solo una portada con foto artística sin experiencia previa',
      'Un documento genérico idéntico para cualquier tipo de empresa'
    ],
    correctIndex: 0,
    explanation: 'Los reclutadores valoran CVs de 1-2 páginas focalizados en resultados medibles e impacto demostrado.',
    category: 'Empleabilidad',
  },
  {
    id: 'q2',
    question: '¿Cómo funciona el Método STAR al responder sobre situaciones pasadas en una entrevista?',
    options: [
      'Describe: Situación inicial, Tarea a cumplir, Acción personal y Resultado obtenido',
      'Hablar de forma abstracta sin dar detalles para no equivocarse',
      'Contar lo que hizo todo el equipo atribuyéndote el 100% del mérito',
      'Esperar a que el entrevistador adivine las acciones realizadas'
    ],
    correctIndex: 0,
    explanation: 'El método STAR (Situation, Task, Action, Result) proporciona una respuesta estructurada con evidencia sólida de competencias.',
    category: 'Entrevistas por Competencias',
  },
  {
    id: 'q3',
    question: 'Frente a un conflicto o desacuerdo técnico en tu equipo, ¿cuál es la mejor postura de liderazgo?',
    options: [
      'Fomentar la escucha activa, enfocar el problema (no a las personas) y buscar consensos objetivos',
      'Imponer tu punto de vista de inmediato para no perder tiempo en debates',
      'Ignorar el desacuerdo esperando que se solucione por sí solo con el tiempo',
      'Elevar una queja formal antes de dialogar con las partes involucradas'
    ],
    correctIndex: 0,
    explanation: 'La resolución constructiva de conflictos fortalece la confianza y la cohesión de equipos de alto rendimiento.',
    category: 'Liderazgo y Trabajo en Equipo',
  },
  {
    id: 'q4',
    question: '¿Qué caracteriza a una verdadera cultura de retroalimentación (Feedback) continuo?',
    options: [
      'Conversaciones oportunas, bidireccionales y orientadas al aprendizaje y desarrollo continuo',
      'Una reunión anual punitiva donde solo se destacan los errores cometidos',
      'Comentarios negativos expresados en público para ejemplificar al grupo',
      'Elogios constantes sin sugerencias de mejora ni planes de acción'
    ],
    correctIndex: 0,
    explanation: 'El feedback continuo y constructivo permite corregir desviaciones a tiempo e impulsa el crecimiento mutuo.',
    category: 'Cultura Organizacional',
  },
  {
    id: 'q5',
    question: '¿Qué es la mentalidad de "Learnability" y por qué es una de las más buscadas en banca y tecnología?',
    options: [
      'La curiosidad y capacidad de desaprender y aprender rápidamente nuevas competencias',
      'Memorizar normas rígidas y resistirse a las nuevas tecnologías',
      'Tener títulos académicos antiguos sin actualizar conocimientos en la práctica',
      'Esperar que la empresa te obligue a capacitarte sin iniciativa propia'
    ],
    correctIndex: 0,
    explanation: 'En entornos dinámicos, la adaptabilidad y el aprendizaje autónomo superan a los conocimientos estáticos.',
    category: 'Desarrollo Profesional',
  },
  {
    id: 'q6',
    question: 'Al recibir múltiples tareas urgentes e importantes, ¿qué herramienta de gestión del tiempo es ideal?',
    options: [
      'La Matriz de Eisenhower para priorizar lo urgente vs lo importante y planificar',
      'Hacer multitasking desordenado saltando de una tarea a otra sin terminar ninguna',
      'Postergar las tareas complejas hasta el último minuto de la jornada',
      'Hacer solo lo que sea más fácil ignorando el impacto en el negocio'
    ],
    correctIndex: 0,
    explanation: 'La Matriz de Eisenhower ayuda a clasificar actividades por impacto y urgencia, reduciendo el estrés laboral.',
    category: 'Productividad y Enfoque',
  },
  {
    id: 'q7',
    question: '¿Por qué es fundamental investigar el propósito y valores de BancoSol antes de tu entrevista?',
    options: [
      'Para validar la afinidad cultural (fit cultural) y conectar tu experiencia con su misión de inclusión social',
      'Solo para repetir de memoria la fecha de fundación de la entidad',
      'No tiene utilidad porque todas las entidades financieras tienen la misma cultura',
      'Para exigir beneficios antes de conocer las responsabilidades del puesto'
    ],
    correctIndex: 0,
    explanation: 'Entender la vocación de inclusión social y microfinanzas de BancoSol demuestra compromiso genuino con su impacto.',
    category: 'Cultura BancoSol',
  },
];

export const DEFAULT_PAIR_CARDS: PairCard[] = [
  { id: 'p1_a', concept: 'Liderazgo Servicial', pairConcept: 'Empatía y Desarrollo de Otros', matchId: 'm1', icon: '👑' },
  { id: 'p1_b', concept: 'Empatía y Desarrollo de Otros', pairConcept: 'Liderazgo Servicial', matchId: 'm1', icon: '👑' },
  
  { id: 'p2_a', concept: 'Método STAR', pairConcept: 'Situación, Tarea, Acción, Resultado', matchId: 'm2', icon: '🎯' },
  { id: 'p2_b', concept: 'Situación, Tarea, Acción, Resultado', pairConcept: 'Método STAR', matchId: 'm2', icon: '🎯' },
  
  { id: 'p3_a', concept: 'Feedback Continuo', pairConcept: 'Escucha Asertiva y Crecimiento', matchId: 'm3', icon: '💬' },
  { id: 'p3_b', concept: 'Escucha Asertiva y Crecimiento', pairConcept: 'Feedback Continuo', matchId: 'm3', icon: '💬' },

  { id: 'p4_a', concept: 'Innovación Ágil', pairConcept: 'Co-creación y Experimentación', matchId: 'm4', icon: '💡' },
  { id: 'p4_b', concept: 'Co-creación y Experimentación', pairConcept: 'Innovación Ágil', matchId: 'm4', icon: '💡' },

  { id: 'p5_a', concept: 'Resiliencia Laboral', pairConcept: 'Adaptación Positiva al Cambio', matchId: 'm5', icon: '🛡️' },
  { id: 'p5_b', concept: 'Adaptación Positiva al Cambio', pairConcept: 'Resiliencia Laboral', matchId: 'm5', icon: '🛡️' },

  { id: 'p6_a', concept: 'Inclusión Financiera', pairConcept: 'Oportunidades para Microemprendedores', matchId: 'm6', icon: '🌱' },
  { id: 'p6_b', concept: 'Oportunidades para Microemprendedores', pairConcept: 'Inclusión Financiera', matchId: 'm6', icon: '🌱' },
];

export const DEFAULT_SWIPE_CARDS: SwipeCard[] = [
  {
    id: 's1',
    statement: '“Un currículum de 6 páginas es mejor porque demuestra que tienes muchísima experiencia.”',
    isReal: false,
    feedback: '¡MITO! La brevedad, claridad y enfoque en logros clave (1-2 págs.) superan por mucho a los CVs extensos.',
    topic: 'Curriculum Vitae',
  },
  {
    id: 's2',
    statement: '“Las habilidades blandas (Soft Skills) como la empatía y la comunicación son tan decisivas como los conocimientos técnicos.”',
    isReal: true,
    feedback: '¡REALIDAD! En procesos de selección modernos, la actitud, trabajo en equipo y adaptabilidad definen la contratación.',
    topic: 'Competencias Clave',
  },
  {
    id: 's3',
    statement: '“Hacer preguntas inteligentes al reclutador al final de la entrevista se percibe como falta de respeto.”',
    isReal: false,
    feedback: '¡MITO! Preguntar demuestra proactividad, preparación, curiosidad y genuino interés en el equipo.',
    topic: 'Entrevistas de Trabajo',
  },
  {
    id: 's4',
    statement: '“El aprendizaje continuo (Upskilling & Reskilling) es indispensable para mantenerse vigente en la era digital.”',
    isReal: true,
    feedback: '¡REALIDAD! La velocidad de transformación exige capacitarse y actualizar habilidades constantemente.',
    topic: 'Desarrollo Profesional',
  },
  {
    id: 's5',
    statement: '“En una entrevista laboral está prohibido admitir que alguna vez cometiste un error en un proyecto.”',
    isReal: false,
    feedback: '¡MITO! Compartir cómo superaste un error y qué aprendizaje obtuviste demuestra madurez, humildad y resiliencia.',
    topic: 'Inteligencia Emocional',
  },
  {
    id: 's6',
    statement: '“Tener un perfil activo y actualizado en LinkedIn aumenta significativamente la visibilidad ante reclutadores.”',
    isReal: true,
    feedback: '¡REALIDAD! Más del 85% de las empresas utilizan redes profesionales para reclutar talento activamente.',
    topic: 'Marca Personal',
  },
  {
    id: 's7',
    statement: '“El salario económico es el único factor que determina la satisfacción y retención del talento humano.”',
    isReal: false,
    feedback: '¡MITO! El salario emocional (clima laboral, balance vida-trabajo, reconocimiento y propósito) es determinante.',
    topic: 'Salario Emocional',
  },
  {
    id: 's8',
    statement: '“La diversidad de perspectivas e inclusión en los equipos impulsa la innovación y mejores decisiones financieras.”',
    isReal: true,
    feedback: '¡REALIDAD! Equipos diversos e inclusivos resuelven problemas complejos con mayor creatividad y efectividad.',
    topic: 'Diversidad e Inclusión',
  },
];

export const DEFAULT_ROULETTE_SLICES: RouletteSlice[] = [
  { id: 'r1', label: 'PREMIO DIRECTO', icon: '🎁', isWinner: true, prizeText: 'Kit de Marca Empleadora BancoSol', color: '#f97316', weight: 25 },
  { id: 'r2', label: 'ESTRELLA BANCOSOL', icon: '⭐', isWinner: true, prizeText: 'Premio Especial de Innovación', color: '#4f46e5', weight: 25 },
  { id: 'r3', label: 'RETO DE TALENTO', icon: '⚡', isWinner: true, prizeText: 'Supera el Micro-Dilema para Ganar', color: '#0d9488', weight: 25 },
  { id: 'r4', label: 'OTRA OPORTUNIDAD', icon: '🔄', isWinner: false, prizeText: '¡Intenta de nuevo en tu siguiente turno!', color: '#475569', weight: 10 },
  { id: 'r5', label: 'GRAN TALENTO', icon: '💎', isWinner: true, prizeText: 'Recompensa de Empleabilidad', color: '#9333ea', weight: 20 },
];

export const DEFAULT_CHEST_OPTIONS: ChestOption[] = [
  {
    id: 'c1',
    title: 'Cliente',
    subtitle: 'Crear experiencias únicas y memorables',
    isWinner: true,
    prizeText: '¡Premio de Embajador de Experiencia al Cliente!',
    icon: '🤝',
    color: '#ea580c',
    borderColor: 'border-orange-500/50',
    bgGradient: 'from-orange-500/20 to-amber-600/20',
    challengeQuestion: '¿Cómo activamos el pilar de CLIENTE en el día a día de BancoSol?',
    challengeOptions: [
      'Escuchando con empatía sus metas y diseñando soluciones financieras a su medida.',
      'Ofreciendo productos estándar sin importar la necesidad real del usuario.',
      'Priorizando trámites burocráticos sobre la cercanía humana.',
    ],
    correctChallengeIndex: 0,
    explanation: 'Crear experiencias memorables significa ponerse en los zapatos de cada microempresario boliviano con calidez y soluciones reales.',
  },
  {
    id: 'c2',
    title: 'Innovación',
    subtitle: 'Crear experiencias más simples, ágiles y humanas',
    isWinner: true,
    prizeText: '¡Premio de Transformación y Agilidad Digital!',
    icon: '💡',
    color: '#7c3aed',
    borderColor: 'border-purple-500/50',
    bgGradient: 'from-purple-500/20 to-indigo-600/20',
    challengeQuestion: '¿Cuál es el propósito central de la INNOVACIÓN en BancoSol?',
    challengeOptions: [
      'Hacer los servicios financieros más simples, intuitivos, rápidos y con sentido humano.',
      'Complicar los sistemas con tecnologías que nadie entiende.',
      'Automatizar todo eliminando el contacto y la empatía con las personas.',
    ],
    correctChallengeIndex: 0,
    explanation: 'Innovar no es solo tecnología: es simplificar la vida de las personas de forma ágil, transparente y cercana.',
  },
  {
    id: 'c3',
    title: 'Sostenibilidad',
    subtitle: 'Promover el progreso económico, el desarrollo social inclusivo preservando el medio ambiente',
    isWinner: true,
    prizeText: '¡Premio de Impacto Social y Progreso Sostenible!',
    icon: '🌱',
    color: '#16a34a',
    borderColor: 'border-emerald-500/50',
    bgGradient: 'from-emerald-500/20 to-teal-600/20',
    challengeQuestion: '¿Qué representa la SOSTENIBILIDAD como pilar de BancoSol?',
    challengeOptions: [
      'Impulsar el progreso económico y la inclusión social cuidando activamente el medio ambiente.',
      'Financiar únicamente proyectos sin evaluar su impacto social o ambiental.',
      'Enfocarse solo en resultados de corto plazo sin pensar en las futuras generaciones.',
    ],
    correctChallengeIndex: 0,
    explanation: 'La sostenibilidad une inclusión social, rentabilidad ética y preservación ambiental para generar bienestar duradero.',
  },
  {
    id: 'c4',
    title: 'Talento Humano',
    subtitle: 'Atraer y retener el mejor talento, acompañando su crecimiento a partir de una cultura basada en valores',
    isWinner: true,
    prizeText: '¡Premio de Cultura y Desarrollo de Talento!',
    icon: '👥',
    color: '#2563eb',
    borderColor: 'border-blue-500/50',
    bgGradient: 'from-blue-500/20 to-cyan-600/20',
    challengeQuestion: '¿Cómo se vive el pilar de TALENTO HUMANO en nuestra organización?',
    challengeOptions: [
      'Acompañando el desarrollo continuo de los colaboradores en un entorno de respeto, valores y bienestar.',
      'Limitando la capacitación y las oportunidades de crecimiento interno.',
      'Considerando al talento como un recurso transaccional sin plan de carrera.',
    ],
    correctChallengeIndex: 0,
    explanation: 'El talento humano es el corazón de BancoSol: su desarrollo, bienestar y valores impulsan el éxito colectivo.',
  },
];
