import { GameDefinition, QuizQuestion, PairCard, SwipeCard, RouletteSlice, ChestOption, AppConfig } from '../types';

export const DEFAULT_APP_CONFIG: AppConfig = {
  eventName: `Feria de Empleabilidad ${new Date().getFullYear()}`,
  eventDate: new Date().toISOString().split('T')[0],
  welcomeMessage: '¡Demuestra tu potencial y gana premios instantáneos con BancoSol!',
  prizesAvailable: true,
  prizesTotalStock: 50,
  prizesRemaining: 42,
  prizeName: 'Kit de Marca Empleadora BancoSol',
  autoResetSeconds: 25,
  activeGames: {
    maze: true,
    quiz: true,
    roulette: true,
    chests: true,
    pairs: true,
    swipe: true,
    catcher: true,
  },
  quizRequiredCorrect: 4,
  googleSheetsWebhookUrl: 'https://script.google.com/macros/s/AKfycbw-95NnIXQVoCeFQuRwpHbTenDHRKtunVuXg-ePmNqVBagcMyRVKuFK9hrlhaJOebtn/exec',
};

export const GAMES_CATALOG: GameDefinition[] = [
  {
    id: 'maze',
    name: 'Laberinto del Talento',
    subtitle: 'Arcade, Estrategia y Desafíos BancoSol',
    description: 'Recorre el laberinto ampliado, responde las 3 preguntas en los Nodos Estrella BancoSol y supera el Burnout.',
    icon: '🧭',
    color: 'from-[#60309B]/40 to-[#2A1544]/60',
    accentColor: '#FF7D00',
    durationText: '60-70 SEG',
    targetDurationSeconds: 65,
    difficulty: 'Estratégico',
    hrTopic: 'Misión, Visión, Resiliencia y Agilidad BancoSol',
    enabled: true,
  },
  {
    id: 'quiz',
    name: 'Quiz Express',
    subtitle: 'Trivia Institucional y de RRHH',
    description: '7 preguntas y dilemas sobre BancoSol, Centro Digital, liderazgo y método STAR. ¡Acierta 5!',
    icon: '⚡',
    color: 'from-[#60309B]/40 to-[#1A0C2B]/60',
    accentColor: '#FF7D00',
    durationText: '60-75 SEG',
    targetDurationSeconds: 70,
    difficulty: 'Desafiante',
    hrTopic: 'Cultura BancoSol, Entrevistas y Centro Digital',
    enabled: true,
  },
  {
    id: 'pairs',
    name: 'Match de Competencias',
    subtitle: 'Memoria y Conceptos BancoSol',
    description: 'Empareja 6 conceptos clave de BancoSol, Centro Digital y cultura de talento antes de 60s.',
    icon: '🧠',
    color: 'from-[#60309B]/35 to-[#1A0C2B]/60',
    accentColor: '#FF7D00',
    durationText: '50-60 SEG',
    targetDurationSeconds: 55,
    difficulty: 'Medio',
    hrTopic: 'Pilares, Inclusión Financiera y Valores',
    enabled: true,
  },
  {
    id: 'swipe',
    name: 'Mito o Realidad de Empleabilidad',
    subtitle: 'Decisión Ágil y Cultura BancoSol',
    description: '8 casos sobre empleabilidad, talento y BancoSol: Desliza Mito (Izquierda) o Realidad (Derecha).',
    icon: '🔥',
    color: 'from-[#60309B]/40 to-[#FF7D00]/20',
    accentColor: '#FF7D00',
    durationText: '50-60 SEG',
    targetDurationSeconds: 55,
    difficulty: 'Dinámico',
    hrTopic: 'Mitos de Empleabilidad, Selección y BancoSol',
    enabled: true,
  },
  {
    id: 'catcher',
    name: 'Colector de Habilidades',
    subtitle: 'Imán del Talento BancoSol',
    description: 'Atrapa conceptos BancoSol (Inclusión, Centro Digital, SolNet) y esquiva antivalores a alta velocidad.',
    icon: '🎯',
    color: 'from-[#60309B]/40 to-[#2A1544]/60',
    accentColor: '#FF7D00',
    durationText: '50-55 SEG',
    targetDurationSeconds: 50,
    difficulty: 'Reflejos',
    hrTopic: 'Valores BancoSol, SolNet y Centro Digital',
    enabled: true,
  },
  {
    id: 'roulette',
    name: 'Ruleta de la Fortuna',
    subtitle: 'Giro y Reto de Talento',
    description: 'Gira la ruleta de BancoSol y completa el micro-reto de empleabilidad para asegurar tu premio.',
    icon: '🎡',
    color: 'from-[#60309B]/40 to-[#FF7D00]/20',
    accentColor: '#FF7D00',
    durationText: '30-40 SEG',
    targetDurationSeconds: 35,
    difficulty: 'Interactivo',
    hrTopic: 'Oportunidades y Dilemas de Crecimiento',
    enabled: true,
  },
  {
    id: 'chests',
    name: 'Los 4 Pilares Estratégicos',
    subtitle: 'Cliente • Innovación • Sostenibilidad • Talento',
    description: 'Elige uno de los 4 pilares BancoSol, resuelve su desafío de alineación y abre tu recompensa.',
    icon: '🏛️',
    color: 'from-[#60309B]/50 via-[#401C68]/40 to-[#FF7D00]/20',
    accentColor: '#FF7D00',
    durationText: '40-50 SEG',
    targetDurationSeconds: 45,
    difficulty: 'Estratégico',
    hrTopic: 'Pilares Estratégicos y Propósito BancoSol',
    enabled: true,
  },
];

export const DEFAULT_QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'q1',
    question: '¿Cuál es la estructura y extensión recomendada para el CV de un postulante?',
    options: [
      '1 a 2 páginas concisas, con logros cuantificables y perfil orientado al rol',
      'Mínimo 5 páginas detallando cada tarea diaria de los últimos 15 años',
      'Solo una portada con foto artística sin experiencia previa',
      'Un documento genérico idéntico para cualquier tipo de empresa'
    ],
    correctIndex: 0,
    explanation: 'Los reclutadores valoran CVs de 1-2 páginas focalizados en resultados medibles e impacto demostrado.',
    category: 'Empleabilidad',
  },
  {
    id: 'q2',
    question: '¿Cómo funciona el Método STAR al responder sobre situaciones pasadas en una entrevista?',
    options: [
      'Describe: Situación inicial, Tarea a cumplir, Acción personal y Resultado obtenido',
      'Hablar de forma abstracta sin dar detalles para no equivocarse',
      'Contar lo que hizo todo el equipo atribuyéndote el 100% del mérito',
      'Esperar a que el entrevistador adivine las acciones realizadas'
    ],
    correctIndex: 0,
    explanation: 'El método STAR (Situation, Task, Action, Result) proporciona una respuesta estructurada con evidencia sólida de competencias.',
    category: 'Entrevistas por Competencias',
  },
  {
    id: 'q3',
    question: 'Frente a un conflicto o desacuerdo técnico en tu equipo, ¿cuál es la mejor postura de liderazgo?',
    options: [
      'Fomentar la escucha activa, enfocar el problema (no a las personas) y buscar consensos objetivos',
      'Imponer tu punto de vista de inmediato para no perder tiempo en debates',
      'Ignorar el desacuerdo esperando que se solucione por sí solo con el tiempo',
      'Elevar una queja formal antes de dialogar con las partes involucradas'
    ],
    correctIndex: 0,
    explanation: 'La resolución constructiva de conflictos fortalece la confianza y la cohesión de equipos de alto rendimiento.',
    category: 'Liderazgo y Trabajo en Equipo',
  },
  {
    id: 'q4',
    question: '¿Qué caracteriza a una verdadera cultura de retroalimentación (Feedback) continuo?',
    options: [
      'Conversaciones oportunas, bidireccionales y orientadas al aprendizaje y desarrollo continuo',
      'Una reunión anual punitiva donde solo se destacan los errores cometidos',
      'Comentarios negativos expresados en público para ejemplificar al grupo',
      'Elogios constantes sin sugerencias de mejora ni planes de acción'
    ],
    correctIndex: 0,
    explanation: 'El feedback continuo y constructivo permite corregir desviaciones a tiempo e impulsa el crecimiento mutuo.',
    category: 'Cultura Organizacional',
  },
  {
    id: 'q5',
    question: '¿Qué es la mentalidad de "Learnability" y por qué es una de las más buscadas en banca y tecnología?',
    options: [
      'La curiosidad y capacidad de desaprender y aprender rápidamente nuevas competencias',
      'Memorizar normas rígidas y resistirse a las nuevas tecnologías',
      'Tener títulos académicos antiguos sin actualizar conocimientos en la práctica',
      'Esperar que la empresa te obligue a capacitarte sin iniciativa propia'
    ],
    correctIndex: 0,
    explanation: 'En entornos dinámicos, la adaptabilidad y el aprendizaje autónomo superan a los conocimientos estáticos.',
    category: 'Desarrollo Profesional',
  },
  {
    id: 'q6',
    question: 'Al recibir múltiples tareas urgentes e importantes, ¿qué herramienta de gestión del tiempo es ideal?',
    options: [
      'La Matriz de Eisenhower para priorizar lo urgente vs lo importante y planificar',
      'Hacer multitasking desordenado saltando de una tarea a otra sin terminar ninguna',
      'Postergar las tareas complejas hasta el último minuto de la jornada',
      'Hacer solo lo que sea más fácil ignorando el impacto en el negocio'
    ],
    correctIndex: 0,
    explanation: 'La Matriz de Eisenhower ayuda a clasificar actividades por impacto y urgencia, reduciendo el estrés laboral.',
    category: 'Productividad y Enfoque',
  },
  {
    id: 'q7',
    question: '¿Por qué es fundamental investigar el propósito y valores de BancoSol antes de tu entrevista?',
    options: [
      'Para validar la afinidad cultural (fit cultural) y conectar tu experiencia con su misión de inclusión social',
      'Solo para repetir de memoria la fecha de fundación de la entidad',
      'No tiene utilidad porque todas las entidades financieras tienen la misma cultura',
      'Para exigir beneficios antes de conocer las responsabilidades del puesto'
    ],
    correctIndex: 0,
    explanation: 'Entender la vocación de inclusión social y microfinanzas de BancoSol demuestra compromiso genuino con su impacto.',
    category: 'Cultura BancoSol',
  },
];

export const DEFAULT_MAZE_QUESTIONS: QuizQuestion[] = [
  {
    id: 'mq1',
    question: '¿Cuál es la misión principal de BancoSol?',
    options: [
      'Transformar la vida de las personas acompañando sus sueños con inclusión y soluciones financieras',
      'Atender solo a multinacionales sin enfoque en inclusión social',
      'Cobrar comisiones excesivas a pequeños microempresarios',
    ],
    correctIndex: 0,
    explanation: 'La misión de BancoSol es transformar vidas mediante la inclusión social y soluciones financieras que impulsan los sueños de los bolivianos.',
    category: 'Misión BancoSol',
  },
  {
    id: 'mq2',
    question: '¿Qué es el Centro Digital de BancoSol y cuál es su objetivo?',
    options: [
      'El hub de innovación donde equipos ágiles crean productos digitales propios para democratizar las finanzas',
      'Un almacén físico donde se guardan archivos en papel',
      'Una oficina tradicional sin acceso a tecnología ni internet',
    ],
    correctIndex: 0,
    explanation: 'El Centro Digital es el motor tecnológico de BancoSol para crear soluciones digitales ágiles, seguras y humanas.',
    category: 'Centro Digital',
  },
  {
    id: 'mq3',
    question: '¿Cuál es la visión que orienta el futuro de BancoSol?',
    options: [
      'Líderes en microfinanzas e inclusión financiera, ágiles, sostenibles y digitales',
      'Mantener procesos manuales y rechazar la evolución digital',
      'Operar únicamente en una sola ciudad sin presencia nacional',
    ],
    correctIndex: 0,
    explanation: 'BancoSol aspira a liderar la inclusión financiera digital y sostenible en Bolivia con impacto social positivo.',
    category: 'Visión BancoSol',
  },
  {
    id: 'mq4',
    question: '¿Qué soluciones digitales destacadas ofrece BancoSol a sus clientes?',
    options: [
      'SolNet, App BancoSol Móvil y GanaSol para transacciones seguras 24/7',
      'Únicamente depósitos físicos en ventanilla sin banca por internet',
      'Sistemas desconectados que requieren trámites de semanas',
    ],
    correctIndex: 0,
    explanation: 'Herramientas como SolNet y App BancoSol permiten a miles de usuarios realizar pagos, ahorros y transferencias inmediatas.',
    category: 'Canales Digitales',
  },
  {
    id: 'mq5',
    question: '¿Por qué el modelo de microfinanzas de BancoSol es pionero a nivel mundial?',
    options: [
      'Por ser el primer banco comercial del mundo dedicado exclusivamente a las microfinanzas con impacto social',
      'Por ser una entidad que no apoya el crecimiento de emprendedores',
      'Por enfocarse únicamente en especulación financiera sin microcréditos',
    ],
    correctIndex: 0,
    explanation: 'BancoSol marcó un hito histórico global al demostrar que las microfinanzas éticas e inclusivas son sostenibles y transformadoras.',
    category: 'Historia e Inclusión',
  },
];

export const DEFAULT_PAIR_CARDS: PairCard[] = [
  { id: 'p1_a', concept: 'Centro Digital', pairConcept: 'Innovación y Soluciones Tecnológicas', matchId: 'm1', icon: '💻' },
  { id: 'p1_b', concept: 'Innovación y Soluciones Tecnológicas', pairConcept: 'Centro Digital', matchId: 'm1', icon: '💻' },
  
  { id: 'p2_a', concept: 'Misión BancoSol', pairConcept: 'Acompañar Sueños con Inclusión', matchId: 'm2', icon: '✨' },
  { id: 'p2_b', concept: 'Acompañar Sueños con Inclusión', pairConcept: 'Misión BancoSol', matchId: 'm2', icon: '✨' },
  
  { id: 'p3_a', concept: 'Visión BancoSol', pairConcept: 'Liderazgo en Microfinanzas Sostenibles', matchId: 'm3', icon: '🌍' },
  { id: 'p3_b', concept: 'Liderazgo en Microfinanzas Sostenibles', pairConcept: 'Visión BancoSol', matchId: 'm3', icon: '🌍' },

  { id: 'p4_a', concept: 'SolNet & App Móvil', pairConcept: 'Banca Digital Ágil y Segura 24/7', matchId: 'm4', icon: '📱' },
  { id: 'p4_b', concept: 'Banca Digital Ágil y Segura 24/7', pairConcept: 'SolNet & App Móvil', matchId: 'm4', icon: '📱' },

  { id: 'p5_a', concept: 'Liderazgo Servicial', pairConcept: 'Empatía y Desarrollo del Equipo', matchId: 'm5', icon: '👑' },
  { id: 'p5_b', concept: 'Empatía y Desarrollo del Equipo', pairConcept: 'Liderazgo Servicial', matchId: 'm5', icon: '👑' },

  { id: 'p6_a', concept: 'Inclusión Financiera', pairConcept: 'Oportunidades para Emprendedores', matchId: 'm6', icon: '🌱' },
  { id: 'p6_b', concept: 'Oportunidades para Emprendedores', pairConcept: 'Inclusión Financiera', matchId: 'm6', icon: '🌱' },
];

export const DEFAULT_SWIPE_CARDS: SwipeCard[] = [
  {
    id: 's1',
    statement: '“Para postular a BancoSol necesitas años de experiencia bancaria; no aceptan talento joven ni recién graduados.”',
    isReal: false,
    feedback: '¡MITO! BancoSol impulsa semilleros de talento joven, pasantías y programas de desarrollo para recién graduados con potencial.',
    topic: 'Talento Joven BancoSol',
  },
  {
    id: 's2',
    statement: '“El Centro Digital de BancoSol diseña productos tecnológicos propios como SolNet y soluciones ágiles de inclusión financiera.”',
    isReal: true,
    feedback: '¡REALIDAD! En el Centro Digital, equipos multidisciplinarios de tecnología e innovación crean software propio para democratizar las finanzas.',
    topic: 'Centro Digital',
  },
  {
    id: 's3',
    statement: '“La misión institucional de BancoSol es transformar la vida de las personas acompañando sus sueños con inclusión y servicios financieros.”',
    isReal: true,
    feedback: '¡REALIDAD! La inclusión social y el acompañamiento real a los microempresarios son la esencia viva de BancoSol.',
    topic: 'Misión Institucional',
  },
  {
    id: 's4',
    statement: '“En los procesos de selección de BancoSol, los valores como la ética, empatía y trabajo en equipo son tan determinantes como la habilidad técnica.”',
    isReal: true,
    feedback: '¡REALIDAD! El calce cultural con nuestro propósito social y el compromiso con las personas son pilares para ingresar.',
    topic: 'Cultura y Valores',
  },
  {
    id: 's5',
    statement: '“Para trabajar en innovación financiera en BancoSol es obligatorio haber estudiado únicamente Finanzas o Contabilidad.”',
    isReal: false,
    feedback: '¡MITO! La transformación digital de BancoSol reúne a ingenieros de software, diseñadores UX, analistas de datos, comunicadores y diversas carreras.',
    topic: 'Diversidad de Perfiles',
  },
  {
    id: 's6',
    statement: '“El modelo de microfinanzas sostenibles de BancoSol combina impacto social positivo con educación y salud financiera para los clientes.”',
    isReal: true,
    feedback: '¡REALIDAD! Promovemos el progreso sostenible cuidando activamente la salud financiera de las familias y microempresas.',
    topic: 'Microfinanzas Sostenibles',
  },
  {
    id: 's7',
    statement: '“Un currículum de 6 páginas es mejor que uno conciso de 1 a 2 páginas al postular a BancoSol.”',
    isReal: false,
    feedback: '¡MITO! Los reclutadores valoran CVs de 1 a 2 páginas focalizados en logros medibles, proyectos y competencias clave.',
    topic: 'Empleabilidad y CV',
  },
  {
    id: 's8',
    statement: '“La curiosidad y la capacidad de aprender rápido (Learnability) son actitudes clave para crecer dentro de BancoSol.”',
    isReal: true,
    feedback: '¡REALIDAD! En un entorno ágil y de constante cambio digital, aprender y adaptarse con proactividad abre grandes oportunidades.',
    topic: 'Desarrollo Continuo',
  },
];

export const DEFAULT_ROULETTE_SLICES: RouletteSlice[] = [
  { id: 'r1', label: 'PREMIO DIRECTO', icon: '🎁', isWinner: true, prizeText: 'Kit de Marca Empleadora BancoSol', color: '#f97316', weight: 25 },
  { id: 'r2', label: 'ESTRELLA BANCOSOL', icon: '⭐', isWinner: true, prizeText: 'Premio Especial de Innovación', color: '#4f46e5', weight: 25 },
  { id: 'r3', label: 'RETO DE TALENTO', icon: '⚡', isWinner: true, prizeText: 'Supera el Micro-Dilema para Ganar', color: '#0d9488', weight: 25 },
  { id: 'r4', label: 'OTRA OPORTUNIDAD', icon: '🔄', isWinner: false, prizeText: '¡Intenta de nuevo en tu siguiente turno!', color: '#475569', weight: 10 },
  { id: 'r5', label: 'GRAN TALENTO', icon: '💎', isWinner: true, prizeText: 'Recompensa de Empleabilidad', color: '#9333ea', weight: 20 },
];

export const DEFAULT_CHEST_OPTIONS: ChestOption[] = [
  {
    id: 'c1',
    title: 'Cliente',
    subtitle: 'Crear experiencias únicas y memorables',
    isWinner: true,
    prizeText: '¡Premio de Embajador de Experiencia al Cliente!',
    icon: '🤝',
    color: '#ea580c',
    borderColor: 'border-orange-500/50',
    bgGradient: 'from-orange-500/20 to-amber-600/20',
    challengeQuestion: '¿Cómo activamos el pilar de CLIENTE en el día a día de BancoSol?',
    challengeOptions: [
      'Escuchando con empatía sus metas y diseñando soluciones financieras a su medida.',
      'Ofreciendo productos estándar sin importar la necesidad real del usuario.',
      'Priorizando trámites burocráticos sobre la cercanía humana.',
    ],
    correctChallengeIndex: 0,
    explanation: 'Crear experiencias memorables significa ponerse en los zapatos de cada microempresario boliviano con calidez y soluciones reales.',
  },
  {
    id: 'c2',
    title: 'Innovación',
    subtitle: 'Crear experiencias más simples, ágiles y humanas',
    isWinner: true,
    prizeText: '¡Premio de Transformación y Agilidad Digital!',
    icon: '💡',
    color: '#7c3aed',
    borderColor: 'border-purple-500/50',
    bgGradient: 'from-purple-500/20 to-indigo-600/20',
    challengeQuestion: '¿Cuál es el propósito central de la INNOVACIÓN en BancoSol?',
    challengeOptions: [
      'Hacer los servicios financieros más simples, intuitivos, rápidos y con sentido humano.',
      'Complicar los sistemas con tecnologías que nadie entiende.',
      'Automatizar todo eliminando el contacto y la empatía con las personas.',
    ],
    correctChallengeIndex: 0,
    explanation: 'Innovar no es solo tecnología: es simplificar la vida de las personas de forma ágil, transparente y cercana.',
  },
  {
    id: 'c3',
    title: 'Sostenibilidad',
    subtitle: 'Promover el progreso económico, el desarrollo social inclusivo preservando el medio ambiente',
    isWinner: true,
    prizeText: '¡Premio de Impacto Social y Progreso Sostenible!',
    icon: '🌱',
    color: '#16a34a',
    borderColor: 'border-emerald-500/50',
    bgGradient: 'from-emerald-500/20 to-teal-600/20',
    challengeQuestion: '¿Qué representa la SOSTENIBILIDAD como pilar de BancoSol?',
    challengeOptions: [
      'Impulsar el progreso económico y la inclusión social cuidando activamente el medio ambiente.',
      'Financiar únicamente proyectos sin evaluar su impacto social o ambiental.',
      'Enfocarse solo en resultados de corto plazo sin pensar en las futuras generaciones.',
    ],
    correctChallengeIndex: 0,
    explanation: 'La sostenibilidad une inclusión social, rentabilidad ética y preservación ambiental para generar bienestar duradero.',
  },
  {
    id: 'c4',
    title: 'Talento Humano',
    subtitle: 'Atraer y retener el mejor talento, acompañando su crecimiento a partir de una cultura basada en valores',
    isWinner: true,
    prizeText: '¡Premio de Cultura y Desarrollo de Talento!',
    icon: '👥',
    color: '#2563eb',
    borderColor: 'border-blue-500/50',
    bgGradient: 'from-blue-500/20 to-cyan-600/20',
    challengeQuestion: '¿Cómo se vive el pilar de TALENTO HUMANO en nuestra organización?',
    challengeOptions: [
      'Acompañando el desarrollo continuo de los colaboradores en un entorno de respeto, valores y bienestar.',
      'Limitando la capacitación y las oportunidades de crecimiento interno.',
      'Considerando al talento como un recurso transaccional sin plan de carrera.',
    ],
    correctChallengeIndex: 0,
    explanation: 'El talento humano es el corazón de BancoSol: su desarrollo, bienestar y valores impulsan el éxito colectivo.',
  },
];
